## Last commit: 2026-10-09 22:14:48 UTC by root
version 20250924.203317_builder.r1513902;
interfaces {
    eth1 {
        unit 12 {
            vlan-id 12;
            family inet {
                address 10.0.12.1/24;
            }
        }
        unit 13 {
            vlan-id 13;
            family inet {
                address 10.0.13.1/24;
            }
        }
    }
    lo0 {
        unit 0 {
            family inet {
                address 10.1.1.1/32;
            }
        }
    }
}
routing-options {
    router-id 10.1.1.1;
}
protocols {
    ospf {
        area 0.0.0.0 {
            interface lo0.0 {
                passive;
            }
            interface eth1.12 {
                priority 255;
            }
        }
        area 0.0.0.1 {
            interface eth1.13 {
                interface-type p2p;
            }
        }
    }
}
