module(load="imudp")
input(type="imudp" port="514" address="192.168.121.20")

module(load="imtcp")
input(type="imtcp" port="514" address="192.168.121.20")

template(name="FndLabFormat" type="string"
         string="%timegenerated% %hostname% %syslogtag%%msg%\\n")

action(type="omfile" file="/var/log/fnd-services/remote.log" template="FndLabFormat")
& stop
