system {
    host-name CRPD-LAB1;
    services {
        ssh;
    }
}
routing-options {
    router-id 1.1.1.1;
}
interfaces {
    lo0 {
        unit 0 {
            family inet {
                address 1.1.1.1/32;
            }
        }
    }
}
