system {
    host-name CRPD-LAB2;
    services {
        ssh;
    }
}
routing-options {
    router-id 2.2.2.2;
}
interfaces {
    lo0 {
        unit 0 {
            family inet {
                address 2.2.2.2/32;
            }
        }
    }
}
