system {
    host-name CRPD-LAB3;
    services {
        ssh;
    }
}
routing-options {
    router-id 3.3.3.3;
}
interfaces {
    lo0 {
        unit 0 {
            family inet {
                address 3.3.3.3/32;
            }
        }
    }
}
