FROM ghcr.io/srl-labs/network-multitool:latest

USER root
RUN apk add --no-cache chrony dnsmasq freeradius freeradius-utils openssh-server rsyslog vsftpd supervisor shadow bash \
    && adduser -D -h /home/lab lab \
    && echo 'lab:lab123' | chpasswd \
    && mkdir -p /srv/ftp/archive /var/log/sys101 /run/chrony /run/freeradius /run/sshd \
    && chown -R lab:lab /srv/ftp/archive

COPY chrony.conf /etc/chrony/chrony.conf
COPY chrony.keys /etc/chrony/chrony.keys
COPY dnsmasq.conf /etc/dnsmasq.conf
COPY radius-clients.conf /etc/raddb/clients.conf
COPY radius-users /etc/raddb/users
COPY rsyslog.conf /etc/rsyslog.conf
COPY vsftpd.conf /etc/vsftpd/vsftpd.conf
COPY sshd_config /etc/ssh/sshd_config
COPY supervisord.conf /etc/supervisord.conf
COPY healthcheck.sh /usr/local/bin/healthcheck.sh
COPY start-sys101.sh /usr/local/bin/start-sys101.sh
RUN chmod 600 /etc/chrony/chrony.keys \
    && chown root:radius /etc/raddb/clients.conf /etc/raddb/users \
    && chmod 640 /etc/raddb/clients.conf /etc/raddb/users \
    && chmod +x /usr/local/bin/healthcheck.sh /usr/local/bin/start-sys101.sh \
    && ssh-keygen -A

EXPOSE 21/tcp 22/tcp 53/tcp 53/udp 123/udp 1812/udp 1813/udp 514/tcp 514/udp
HEALTHCHECK --interval=20s --timeout=5s --retries=12 CMD /usr/local/bin/healthcheck.sh
CMD ["/usr/local/bin/start-sys101.sh"]
