[supervisord]
nodaemon=true
user=root
logfile=/var/log/sys101/supervisord.log
pidfile=/run/supervisord.pid

[program:chronyd]
command=/usr/sbin/chronyd -d -x -f /etc/chrony/chrony.conf
autorestart=true

[program:dnsmasq]
command=/usr/sbin/dnsmasq --no-daemon --conf-file=/etc/dnsmasq.conf
autorestart=true

[program:radius]
command=/usr/sbin/radiusd -f -l stdout
autorestart=true

[program:rsyslog]
command=/usr/sbin/rsyslogd -n
autorestart=true

[program:sshd]
command=/usr/sbin/sshd -D -e -f /etc/ssh/sshd_config
autorestart=true

[program:vsftpd]
command=/usr/sbin/vsftpd /etc/vsftpd/vsftpd.conf
autorestart=true
