system {
    host-name R2-BOOTSTRAP;
    root-authentication {
        encrypted-password "$6$SYS101$rCBGUIPw5N.EUdMmg9fb.IV.R6F4eNTzcfKIW0Zyw.mQ4yh4VGw/nm8Hl2wKsaGCtuBv8FtIH52Vlpgmb6YhI0";
    }
    login {
        user lab {
            class super-user;
            authentication {
                encrypted-password "$6$SYS101$rCBGUIPw5N.EUdMmg9fb.IV.R6F4eNTzcfKIW0Zyw.mQ4yh4VGw/nm8Hl2wKsaGCtuBv8FtIH52Vlpgmb6YhI0";
            }
        }
    }
    services {
        ssh;
        netconf {
            ssh;
        }
    }
}
