# Isolated-lab NTP server
port 123

bindaddress 192.168.122.20
binddevice eth1
allow 192.168.122.0/24

local stratum 10

bindcmdaddress 127.0.0.1
cmdport 323

makestep 1.0 3
rtcsync
driftfile /var/lib/chrony/chrony.drift
