port=53
interface=eth0
listen-address=192.168.121.20
bind-interfaces
no-resolv
no-hosts
domain-needed
bogus-priv

domain=fndlab
local=/fndlab/

address=/services.fndlab/192.168.121.20
address=/radius.fndlab/192.168.121.20
address=/syslog.fndlab/192.168.121.20
address=/snmp.fndlab/192.168.121.20
address=/web.fndlab/192.168.121.20

# Palo Alto management record used by FND-101 after PA is moved to a static IP.
address=/pa1.fndlab/192.168.121.10
