client localhost {
    ipaddr = 127.0.0.1
    secret = labsecret
    shortname = localhost
}

client service {
    ipaddr = 192.168.121.20
    secret = labsecret
    shortname = service
}

client pa1 {
    ipaddr = 192.168.121.10
    secret = labsecret
    shortname = pa1
}
