## Last commit: 2026-10-09 22:14:48 UTC by root
version 20250924.203317_builder.r1513902;
interfaces {
    eth1 {
        unit 12 {
            vlan-id 12;
            family inet {
                address 10.0.12.2/24;
            }
        }
        unit 24 {
            vlan-id 24;
            family inet {
                address 10.0.24.2/24;
            }
        }
    }
    lo0 {
        unit 0 {
            family inet {
                address 10.1.1.2/32;
            }
        }
    }
}
routing-options {
    router-id 10.1.1.2;
}
protocols {
    ospf {
        area 0.0.0.0 {
            interface lo0.0 {
                passive;
            }
            interface eth1.12 {
                priority 100;
            }
        }
        area 0.0.0.2 {
            interface eth1.24 {
                interface-type p2p;
            }
        }
    }
}
