## Last commit: 2026-10-09 13:53:26 UTC by root
version 20250924.203317_builder.r1513902;
interfaces {
    eth1 {
        unit 24 {
            vlan-id 24;
            family inet {
                address 10.0.24.4/24;
            }
        }
    }
    eth2 {
        unit 0 {
            family inet {
                address 192.168.16.1/30;
            }
        }
    }
    eth3 {
        unit 0 {
            family inet {
                address 192.168.17.1/24;
            }
        }
    }
    eth4 {
        unit 0 {
            family inet {
                address 192.168.18.1/23;
            }
        }
    }
    lo0 {
        unit 0 {
            family inet {
                address 10.1.1.4/32;
            }
        }
    }
}
