system {
    host-name R1;
    root-authentication {
        encrypted-password "$6$LAB001Junos$qHr8CuT1soYYP/DDM94IlOxaX7UJsbvffksxbWalvkylwQGrJsEdwGdYwtZjCYYybd6t0q0xDQxhW63oCbuog0";
    }
    login {
        user admin {
            uid 2000;
            class super-user;
            authentication {
                encrypted-password "$6$LAB001Junos$qHr8CuT1soYYP/DDM94IlOxaX7UJsbvffksxbWalvkylwQGrJsEdwGdYwtZjCYYybd6t0q0xDQxhW63oCbuog0";
            }
        }
    }
    services {
        ssh {
            root-login allow;
        }
        netconf {
            ssh;
        }
    }
    time-zone Asia/Jakarta;
    management-instance;
    syslog {
        file messages {
            any notice;
            authorization info;
        }
        file interactive-commands {
            interactive-commands any;
        }
    }
}
interfaces {
    ge-0/0/0 {
        description CLIENT1-LAN;
        unit 0 {
            family inet {
                address 192.168.40.1/24;
            }
        }
    }
    ge-0/0/1 {
        description R1-TO-R2-PRIMARY;
        unit 0 {
            family inet {
                address 10.0.12.1/30;
            }
            family mpls;
        }
    }
    ge-0/0/2 {
        description R1-TO-R3-BACKUP;
        unit 0 {
            family inet {
                address 10.0.13.1/30;
            }
            family mpls;
        }
    }
    lo0 {
        unit 0 {
            family inet {
                address 10.255.4.1/32;
            }
        }
    }
}
routing-options {
    router-id 10.255.4.1;
    autonomous-system 65000;
}
protocols {
    mpls {
        interface ge-0/0/1.0;
        interface ge-0/0/2.0;
    }
    ldp {
        transport-address router-id;
        interface ge-0/0/1.0;
        interface ge-0/0/2.0;
        interface lo0.0;
    }
    ospf {
        traffic-engineering;
        area 0.0.0.0 {
            interface ge-0/0/1.0 {
                interface-type p2p;
                metric 10;
            }
            interface ge-0/0/2.0 {
                interface-type p2p;
                metric 50;
            }
            interface lo0.0 {
                passive;
            }
        }
    }
    bgp {
        group CORE-IBGP {
            type internal;
            local-address 10.255.4.1;
            family inet {
                unicast;
            }
            export EXPORT-CLIENT-LAN;
            neighbor 10.255.4.4;
        }
    }
}
policy-options {
    policy-statement EXPORT-CLIENT-LAN {
        term CLIENT-LAN {
            from {
                protocol direct;
                route-filter 192.168.40.0/24 exact;
            }
            then accept;
        }
        term REJECT-OTHER {
            then reject;
        }
    }
}
