system {
    host-name R2;
    root-authentication {
        encrypted-password "$6$LAB001Junos$qHr8CuT1soYYP/DDM94IlOxaX7UJsbvffksxbWalvkylwQGrJsEdwGdYwtZjCYYybd6t0q0xDQxhW63oCbuog0";
    }
    login {
        user admin {
            uid 2000;
            class super-user;
            authentication {
                encrypted-password "$6$LAB001Junos$qHr8CuT1soYYP/DDM94IlOxaX7UJsbvffksxbWalvkylwQGrJsEdwGdYwtZjCYYybd6t0q0xDQxhW63oCbuog0";
            }
        }
    }
    services {
        ssh {
            root-login allow;
        }
        netconf {
            ssh;
        }
    }
    time-zone Asia/Jakarta;
    management-instance;
    syslog {
        file messages {
            any notice;
            authorization info;
        }
        file interactive-commands {
            interactive-commands any;
        }
    }
}
interfaces {
    ge-0/0/0 {
        description R2-TO-R1-PRIMARY;
        unit 0 {
            family inet {
                address 10.0.12.2/30;
            }
            family mpls;
        }
    }
    ge-0/0/1 {
        description R2-TO-R4-PRIMARY;
        unit 0 {
            family inet {
                address 10.0.24.1/30;
            }
            family mpls;
        }
    }
    lo0 {
        unit 0 {
            family inet {
                address 10.255.4.2/32;
            }
        }
    }
}
routing-options {
    router-id 10.255.4.2;
    autonomous-system 65000;
}
protocols {
    mpls {
        interface ge-0/0/0.0;
        interface ge-0/0/1.0;
    }
    ldp {
        transport-address router-id;
        interface ge-0/0/0.0;
        interface ge-0/0/1.0;
        interface lo0.0;
    }
    ospf {
        traffic-engineering;
        area 0.0.0.0 {
            interface ge-0/0/0.0 {
                interface-type p2p;
                metric 10;
            }
            interface ge-0/0/1.0 {
                interface-type p2p;
                metric 10;
            }
            interface lo0.0 {
                passive;
            }
        }
    }
}
