system {
    host-name R1;
    root-authentication {
        encrypted-password "$6$LAB001Junos$qHr8CuT1soYYP/DDM94IlOxaX7UJsbvffksxbWalvkylwQGrJsEdwGdYwtZjCYYybd6t0q0xDQxhW63oCbuog0";
    }
    login {
        user admin {
            uid 2000;
            class super-user;
            authentication {
                encrypted-password "$6$LAB001Junos$qHr8CuT1soYYP/DDM94IlOxaX7UJsbvffksxbWalvkylwQGrJsEdwGdYwtZjCYYybd6t0q0xDQxhW63oCbuog0";
            }
        }
    }
    services {
        ssh { root-login allow; }
        netconf { ssh; }
    }
    time-zone Asia/Jakarta;
    management-instance;
}
interfaces {
    ge-0/0/0 {
        description CLIENT1-LAN;
        unit 0 { family inet { address 192.168.20.1/24; } }
    }
    ge-0/0/1 {
        description R1-TO-R2;
        unit 0 { family inet { address 10.0.12.1/30; } }
    }
    ge-0/0/2 {
        description R1-TO-R3;
        unit 0 { family inet { address 10.0.13.1/30; } }
    }
    lo0 { unit 0 { family inet { address 10.255.0.1/32; } } }
}
routing-options {
    static {
        route 10.255.0.2/32 next-hop 10.0.12.2;
        route 10.255.0.3/32 next-hop 10.0.13.2;
    }
}
