system {
    host-name R1;
}
routing-options {
    router-id 1.1.1.1;
}
interfaces {
    lo0 {
        unit 0 {
            family inet {
                address 1.1.1.1/32;
            }
            family iso {
                address 49.0001.0000.0000.0001.00;
            }
        }
    }
    eth1 {
        unit 0 {
            family inet {
                address 10.0.12.1/30;
            }
            family iso { }
        }
    }
}
protocols {
    isis {
        level 1 disable;
        interface lo0.0 {
            passive;
        }
        interface eth1.0 {
            level 2 {
                metric 10;
            }
        }
    }
}
