system {
    host-name R3;
}
routing-options {
    router-id 3.3.3.3;
}
interfaces {
    lo0 {
        unit 0 {
            family inet {
                address 3.3.3.3/32;
            }
            family iso {
                address 49.0001.0000.0000.0003.00;
            }
        }
    }
    eth1 {
        unit 0 {
            family inet {
                address 10.0.23.2/30;
            }
            family iso { }
        }
    }
}
protocols {
    isis {
        level 1 disable;
        interface lo0.0 {
            passive;
        }
        interface eth1.0 {
            level 2 {
                metric 10;
            }
        }
    }
}
