system {
    host-name R3;
    root-authentication {
        encrypted-password "$6$LAB001Junos$qHr8CuT1soYYP/DDM94IlOxaX7UJsbvffksxbWalvkylwQGrJsEdwGdYwtZjCYYybd6t0q0xDQxhW63oCbuog0";
    }
    login {
        user admin {
            uid 2000;
            class super-user;
            authentication {
                encrypted-password "$6$LAB001Junos$qHr8CuT1soYYP/DDM94IlOxaX7UJsbvffksxbWalvkylwQGrJsEdwGdYwtZjCYYybd6t0q0xDQxhW63oCbuog0";
            }
        }
    }
    services {
        ssh {
            root-login allow;
        }
        netconf {
            ssh;
        }
    }
    time-zone Asia/Jakarta;
    management-instance;
    syslog {
        file messages {
            any notice;
            authorization info;
        }
        file interactive-commands {
            interactive-commands any;
        }
    }
}
interfaces {
    ge-0/0/0 {
        description R3-TO-R2;
        unit 0 {
            family inet {
                address 10.0.23.2/30;
            }
        }
    }
    ge-0/0/1 {
        description R3-TO-R4;
        unit 0 {
            family inet {
                address 10.0.34.1/30;
            }
        }
    }
    lo0 {
        unit 0 {
            family inet {
                address 10.255.0.3/32;
            }
        }
    }
}
routing-options {
    static {
        route 192.168.30.0/24 next-hop 10.0.23.1;
        route 10.0.12.0/30 next-hop 10.0.23.1;
        route 10.255.0.1/32 next-hop 10.0.23.1;
        route 10.255.0.2/32 next-hop 10.0.23.1;
        route 10.255.0.4/32 next-hop 10.0.34.2;
    }
}
