port=53
interface=eth1
listen-address=192.168.122.20
bind-interfaces

no-resolv
no-hosts

domain-needed
bogus-priv

domain=fndlab
local=/fndlab/

address=/pa1.fndlab/192.168.122.10
address=/services.fndlab/192.168.122.20
