system {
    host-name R1;
    root-authentication {
        encrypted-password "$6$rounds=10000$lab$JbQmYpP9wB8mLJvQzPq2mA9nL7wD8qW0";
    }
    login {
        user admin {
            uid 2000;
            class super-user;
            authentication {
                plain-text-password "admin@123";
            }
        }
    }
}
interfaces {
    ge-0/0/0 {
        unit 0 { family inet { address 172.16.15.1/24; } }
    }
    ge-0/0/1 {
        unit 0 { family inet { address 10.0.12.1/30; } }
    }
    lo0 {
        unit 0 {
            family inet {
                address 10.255.5.1/32;
                address 10.10.10.10/32;
                address 10.10.20.20/32;
                address 10.10.20.200/32;
                address 10.10.30.130/32;
                address 10.10.40.40/32;
                address 10.20.10.10/32;
            }
        }
    }
}
routing-options {
    autonomous-system 65001;
    static {
        route 10.10.10.0/24 discard;
        route 10.10.20.0/24 discard;
        route 10.10.20.128/25 discard;
        route 10.10.30.128/25 discard;
        route 10.10.40.0/24 discard;
        route 10.20.10.0/24 discard;
    }
}
policy-options {
    policy-statement EXPORT-TEST-PREFIXES {
        term ACCEPT-TEST {
            from protocol static;
            then accept;
        }
        term REJECT-OTHER {
            then reject;
        }
    }
}
protocols {
    bgp {
        group TO-R2 {
            type external;
            peer-as 65002;
            neighbor 10.0.12.2 {
                export EXPORT-TEST-PREFIXES;
            }
        }
    }
}
