system {
    host-name R2;
    login {
        user admin {
            uid 2000;
            class super-user;
            authentication { plain-text-password "admin@123"; }
        }
    }
}
interfaces {
    ge-0/0/0 { unit 0 { family inet { address 10.0.12.2/30; } } }
    ge-0/0/1 { unit 0 { family inet { address 10.0.23.1/30; } } }
    lo0 { unit 0 { family inet { address 10.255.5.2/32; } } }
}
routing-options { autonomous-system 65002; }
policy-options {
    policy-statement EXPORT-ALL {
        term ALL { then accept; }
    }
}
protocols {
    bgp {
        group FROM-R1 {
            type external;
            peer-as 65001;
            neighbor 10.0.12.1 { }
        }
        group TO-R3 {
            type external;
            peer-as 65003;
            neighbor 10.0.23.2 {
                export EXPORT-ALL;
            }
        }
    }
}
