system {
    host-name R3;
    login {
        user admin {
            uid 2000;
            class super-user;
            authentication { plain-text-password "admin@123"; }
        }
    }
}
interfaces {
    ge-0/0/0 { unit 0 { family inet { address 10.0.23.2/30; } } }
    ge-0/0/1 { unit 0 { family inet { address 10.0.34.1/30; } } }
    lo0 { unit 0 { family inet { address 10.255.5.3/32; } } }
}
routing-options { autonomous-system 65003; }
policy-options {
    policy-statement EXPORT-ALL {
        term ALL { then accept; }
    }
}
protocols {
    bgp {
        group FROM-R2 {
            type external;
            peer-as 65002;
            neighbor 10.0.23.1 { }
        }
        group TO-R4 {
            type external;
            peer-as 65004;
            neighbor 10.0.34.2 {
                export EXPORT-ALL;
            }
        }
    }
}
