system {
    host-name R4;
    login {
        user admin {
            uid 2000;
            class super-user;
            authentication { plain-text-password "admin@123"; }
        }
    }
}
interfaces {
    ge-0/0/0 { unit 0 { family inet { address 10.0.34.2/30; } } }
    ge-0/0/1 { unit 0 { family inet { address 172.16.45.1/24; } } }
    lo0 { unit 0 { family inet { address 10.255.5.4/32; } } }
}
routing-options { autonomous-system 65004; }
protocols {
    bgp {
        group FROM-R3 {
            type external;
            peer-as 65003;
            neighbor 10.0.34.1 { }
        }
    }
}
