worker_processes 1;
pid /run/nginx.pid;

events {
    worker_connections 128;
}

http {
    access_log /var/log/fnd-services/nginx-access.log;
    error_log /var/log/fnd-services/nginx-error.log;

    server {
        listen 192.168.121.20:80;
        server_name _;
        root /var/www/html;
        index index.html;

        location / {
            try_files $uri $uri/ =404;
        }
    }
}
